/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 boat.gltf --transform
Author: Sayapin Zahar (https://sketchfab.com/sayapin_z)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-boat-81ec8558fa2346969d0138e2396ad4a3
Title: Toy Boat
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/boat-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes["Circle_��������������_0"].geometry}
          material={materials.material}
          position={[24.57, 284.74, -94.64]}
          rotation={[-2.97, -0.67, 1.35]}
          scale={100}
        />
        <mesh
          geometry={nodes["Circle001_��������������_0"].geometry}
          material={materials.material}
          position={[0, -57.23, 602.89]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube006_Checker001_0.geometry}
          material={materials["Checker.001"]}
          position={[0, 10.96, -142.27]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Plane001_��������������_0"].geometry}
          material={materials.material}
          position={[0, 97.2, 174.29]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={
            nodes["������������002_������������������_������_0"].geometry
          }
          material={materials.material_2}
          position={[0.03, -351.52, 287.98]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes["������������_������������_Checker_0"].geometry}
          material={materials.Checker}
          position={[0.03, -215.88, 207.48]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={1481.46}
        />
        <mesh
          geometry={nodes["������������_Material_0"].geometry}
          material={materials.Material}
          position={[0.03, -296.09, 166.69]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={
            nodes["��������������_������������_��������������_������������_0"]
              .geometry
          }
          material={materials.material_5}
          position={[0, -221.59, -211.82]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes["��������������_����������_0"].geometry}
          material={materials.material_6}
          scale={100}
        />
        <mesh
          geometry={nodes["������������_������������_0"].geometry}
          material={materials.material_7}
          position={[0, -221.59, -211.82]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={
            nodes[
              "������������_����������_��������������_����������_����������_0"
            ].geometry
          }
          material={materials.material_8}
          position={[28.79, -112.2, 238.22]}
          rotation={[-3.03, 0.3, -0.03]}
          scale={100}
        />
        <mesh
          geometry={
            nodes["��������������_����������_��������������_����������_0"]
              .geometry
          }
          material={materials.material_9}
          position={[0, 158.15, 166]}
          rotation={[-1.18, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["����������_����������_0"].geometry}
          material={materials.material_10}
          position={[-45.44, -217.71, 208.24]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={
            nodes["��������������_����������������_��������������_0"].geometry
          }
          material={materials.material}
          position={[0, -92.97, 544.29]}
          rotation={[0, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={
            nodes[
              "������������_����������_����������_����������_����������_����������������_������������_0"
            ].geometry
          }
          material={materials.material_11}
          position={[-25, 382.12, -145.63]}
          rotation={[-1.55, -Math.PI / 2, 0]}
          scale={116.08}
        />
        <mesh
          geometry={nodes["��������_��������_0"].geometry}
          material={materials.material_12}
          position={[0, 577.25, 132.76]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[68.15, 68.15, 100]}
        />
        <mesh
          geometry={
            nodes[
              "��������������_��������������������_����������������_��������������_0"
            ].geometry
          }
          material={materials.material}
          position={[0, 66.27, 394.4]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point_��������������_0"].geometry}
          material={materials.material}
          position={[0, 499.84, 232.13]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point001_��������������_0"].geometry}
          material={materials.material}
          position={[0, 467.02, 272.08]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point002_��������������_0"].geometry}
          material={materials.material}
          position={[0, 450.51, 302.36]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point004_��������������_0"].geometry}
          material={materials.material}
          position={[0, 443.56, 96.89]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point005_��������������_0"].geometry}
          material={materials.material}
          position={[0, 521.44, 90.94]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point006_��������������_0"].geometry}
          material={materials.material}
          position={[0, 190.34, -192.08]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point007_��������������_0"].geometry}
          material={materials.material}
          position={[0, 308.35, -13.37]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point008_��������������_0"].geometry}
          material={materials.material}
          position={[-54.58, -65.4, 325.63]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point009_��������������_0"].geometry}
          material={materials.material}
          position={[64.11, -65.4, 165.08]}
          rotation={[-Math.PI / 2, 0, 2.02]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point010_��������������_0"].geometry}
          material={materials.material}
          position={[0, -28.66, 325.13]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={
            nodes["��������������_����������_��������������_����������_0_1"]
              .geometry
          }
          material={materials.material_13}
          position={[33.97, -92.97, 544.29]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point011_��������������_0"].geometry}
          material={materials.material}
          position={[139.67, 227.71, -70.57]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point012_��������������_0"].geometry}
          material={materials.material}
          position={[117.44, 205.02, -23.58]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["Point013_��������������_0"].geometry}
          material={materials.material}
          position={[125.36, 205.02, -244.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/boat-transformed.glb");
